### ISSUE TITLE
No graphs showing for any commit

### ISSUE THREAD

**Issue by christetreault** [nomeata/gipeda#28]
On our site, we have several commits, with many benchmarks. Entries are being created for them, however no graphs are populated.

For instance: http://goto.ucsd.edu/~ctetreau/liquidhaskell-perf/#revision/83a7785ceb20fda557f95775f93f3e577915febc

It just says "Nothing selected... try the buttons in the top right corner.", however if I activate + - and =, there is no change in behavior. You'll notice if you go to http://goto.ucsd.edu/~ctetreau/liquidhaskell-perf/ it lists commits as having graphs (the ones with 0 are expected; they're build failures) Any idea why it might be doing this?

Here's a zip file with our logs folder, site folder, log2csv, and settings.yaml. To compile log2csv, you can copy it to the gipeda project directory and do `cabal exec ghc -- log2csv.hs -o log2csv` (assuming you're using cabal with sandboxes)

https://drive.google.com/file/d/0Bx6BpheCXcBWMjdqZ3p4YV9iY1E/view?usp=sharing

**Comment by nomeata** [comment]
Are you sure your `log2csv` script works as expected? Because
http://goto.ucsd.edu/~ctetreau/liquidhaskell-perf/out/results/275fe0015438a64c016e2e29319f24d4c0f15c30.csv
is empty...

**Comment by christetreault** [comment]
It will be empty if a build fails (or other things of this nature), this is expected. There should be some in there that have data. Ideally, I'd have a "builds successfully benchmark" that is true or false (hence https://github.com/nomeata/gipeda/issues/26).

I became convinced that having missing logs might be causing issues., and decided that it'd be better to generate these empty logs than to not. I've seen it work with these empty logs, the graphs just ignore them.

**Comment by nomeata** [comment]
Ah, I think I see the problem. The system currently has a somewhat global list of „all benchmarks“, which it takes from the final (successful) build. But if you final build does not specify any benchmarks in the results file, then there are – to gipeda  – none to display.

I see that this could be improved. (But how precisely? Keep all benchmarks forever and ever, even if you stopped measuring it since half a year?)

For now, if a build fails, you should _not_ generate a `.log` file for it, and gipeda will simply ignore that commit (which can be confusing as well, I guess).

**Comment by christetreault** [comment]
So, I deleted all the leading failure logs, and I now have a functional site. It looks like we're good to go, thanks!

**Comment by nomeata** [comment]
> It looks like we're good to go, thanks!

\o/
