### ISSUE TITLE
Produce a list of revisions that still need to be checked

### ISSUE THREAD

**Issue by nomeata** [nomeata/gipeda#38]
This might be useful in simple bash-script-based runner setups, and also with feed-gipeda, as discussed in https://github.com/sgraf812/feed-gipeda/issues/5#issuecomment-217722378

**Comment by sgraf812** [comment]
This works fine in most cases, but I still got two problems:
1. I want to be able to run gipeda even if I haven't produced any logs yet. Currently it errors out[1], which prohibits gipeda to generate the necessary backlog
2. Only a minor gripe, but I have to work around it nonetheless: Could you use [`writeFile'`](https://hackage.haskell.org/package/shake-0.15.10/docs/Development-Shake.html#v:writeFile-39-) instead of `writeFileChanged` for writing the backlog?  Currently feed-gipeda relies on the backlog file to be written even if there weren't any changes, so I have to work around it by 'touching' it after each call.

[1] This was when there weren't any benchmark logs or cvs yet:

```
✓ site/out/settings.json done
✓ site/out/tags.txt done
✓ site/out/branches.txt done
✓ site/out/head.txt done
✓ cache done
✓ site/out/latest.txt done
✓ site/out/benchNames.json done
Error when running Shake build system:
* site/out/benchNames.json
* site/out/latest.txt
d3feb16a91bb285ce677fb79381f36e9fcdc0979 has no parent with logs?
```

**Comment by sgraf812** [comment]
Regarding 1., that error just comes up due to the order in which the targets are processed. I found a workaround, namely just passing `--keep-going`. That's also probably the intended way of usage, so I consider that as a non-issue.

Leaves us with the write always behavior ~~, which I can also work around with `--always-make`, I think.~~ That does rerun the targets but doesn't write unchanged files.
